version: "3"
services:
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_USER: user
      INFLUXDB_USER_PASSWORD: pass
      INFLUXDB_DB: boot
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: secret
  dashboard:
    image: grafana/grafana
    links:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/influxdb.yaml:/etc/grafana/provisioning/datasources/influxdb.yaml
      - ./grafana/SpringBootDashboard.json:/var/lib/grafana/dashboards/SpringBoot.json
      - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
volumes:
  influxdb:
  grafana:
